services:
  - type: web
    name: ght-oca-backend
    runtime: docker
    dockerfilePath: flight-proxy/Dockerfile
    dockerContext: flight-proxy
    branch: main
    region: frankfurt
    plan: free
    healthCheckPath: /api/flights/ping
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: FLIGHT_AWARE_KEY_1
        sync: false
      - key: FLIGHT_AWARE_KEY_2
        sync: false